# Generated by Django 4.2.11 on 2025-06-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], default='STUDENT', max_length=9)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('github_auth', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('PENDING', 'Pending')], default='LOCKED', max_length=7)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.member')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.member')),
            ],
        ),
    ]
