version: '1.1'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  backend:
    build: backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file: .env
    command: >
      sh -c "
      chmod +x /wait-for-it.sh &&
      /wait-for-it.sh postgres:5432 -t 10 &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: on-failure
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend/src:/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend