# Generated by Django 4.2.11 on 2024-05-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_courseregistration_course_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_project',
            old_name='course',
            new_name='course_pk',
        ),
        migrations.RenameField(
            model_name='course_project',
            old_name='repo',
            new_name='repo_pk',
        ),
        migrations.RenameField(
            model_name='course_registration',
            old_name='course',
            new_name='course_pk',
        ),
        migrations.RenameField(
            model_name='course_registration',
            old_name='student',
            new_name='student_pk',
        ),
        migrations.AddField(
            model_name='course_project',
            name='course_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course_project',
            name='course_semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_project',
            name='course_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_project',
            name='repo_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course_project',
            name='repo_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='course_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='course_semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='course_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
