# Generated by Django 4.2.11 on 2024-05-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_course_course_project_course_pk_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course_project',
            constraint=models.UniqueConstraint(fields=('course_id', 'course_year', 'course_semester', 'repo_id', 'repo_name'), name='unique_course_project'),
        ),
        migrations.AddConstraint(
            model_name='course_registration',
            constraint=models.UniqueConstraint(fields=('course_id', 'course_year', 'course_semester', 'student_id'), name='unique_course_registration'),
        ),
    ]
