# Generated by Django 4.2.11 on 2024-05-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_project_unique_course_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course_project',
            name='unique_course_project',
        ),
        migrations.RemoveConstraint(
            model_name='course_registration',
            name='unique_course_registration',
        ),
        migrations.RemoveField(
            model_name='course_project',
            name='repo_id',
        ),
        migrations.RemoveField(
            model_name='course_project',
            name='repo_pk',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='student_pk',
        ),
        migrations.AddConstraint(
            model_name='course_project',
            constraint=models.UniqueConstraint(fields=('course_pk', 'course_id', 'course_year', 'course_semester', 'repo_name'), name='unique_course_project'),
        ),
        migrations.AddConstraint(
            model_name='course_registration',
            constraint=models.UniqueConstraint(fields=('course_pk', 'course_id', 'course_year', 'course_semester'), name='unique_course_registration'),
        ),
    ]
