# Generated by Django 4.2.11 on 2024-05-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_repository_contributor_and_more'),
        ('account', '0005_student'),
        ('course', '0009_remove_course_project_unique_course_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course_project',
            name='unique_course_project',
        ),
        migrations.RemoveConstraint(
            model_name='course_registration',
            name='unique_course_registration',
        ),
        migrations.AddField(
            model_name='course_project',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.repository'),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddConstraint(
            model_name='course_project',
            constraint=models.UniqueConstraint(fields=('course_pk', 'course_id', 'course_year', 'course_semester', 'repo', 'repo_name'), name='unique_course_project'),
        ),
        migrations.AddConstraint(
            model_name='course_registration',
            constraint=models.UniqueConstraint(fields=('course_pk', 'course_id', 'course_year', 'course_semester', 'student'), name='unique_course_registration'),
        ),
    ]
