# Generated by Django 4.2.11 on 2024-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_project_unique_course_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_project',
        ),
    ]
