# Generated by Django 4.2.11 on 2024-05-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_repo_commit_repo_commit_unique_repo_commit'),
        ('course', '0011_delete_course_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.IntegerField(null=True)),
                ('course_semester', models.IntegerField(null=True)),
                ('repo_name', models.CharField(max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course_project',
            constraint=models.UniqueConstraint(fields=('course', 'course_year', 'course_semester', 'repo', 'repo_name'), name='unique_course_project'),
        ),
    ]
