# Generated by Django 4.2.11 on 2024-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_project_course_project_unique_course_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_registration',
        ),
    ]
