# Generated by Django 4.2.11 on 2024-05-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_student_college_alter_student_department_and_more'),
        ('course', '0013_delete_course_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.IntegerField(null=True)),
                ('course_semester', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course_registration',
            constraint=models.UniqueConstraint(fields=('course_id', 'course_year', 'course_semester', 'student'), name='unique_course_registration'),
        ),
    ]
