# Generated by Django 4.2.11 on 2024-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_repo_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
