# Generated by Django 4.2.11 on 2024-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('github_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('double_major', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('enrollment', models.CharField(max_length=100)),
                ('follower_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('public_repo_count', models.IntegerField(null=True)),
                ('starred_count', models.IntegerField(null=True)),
                ('github_profile_create_at', models.CharField(max_length=100, null=True)),
                ('github_profile_update_at', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
