# Generated by Django 4.2.11 on 2024-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_that'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hello',
        ),
        migrations.RemoveField(
            model_name='user',
            name='that',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
