# Generated by Django 4.2.11 on 2024-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_hello_remove_user_that_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('github_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('double_major', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('primary_email', models.EmailField(max_length=254, null=True)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('enrollment', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
