# Generated by Django 4.2.11 on 2024-08-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_administration_github_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
