# Generated by Django 4.2.11 on 2024-08-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_administration_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
