# Generated by Django 4.2.11 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_administration_is_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_language_percentage',
            field=models.JSONField(null=True),
        ),
    ]
