# Generated by Django 4.2.11 on 2025-10-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_student_total_language_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='technology_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
