# Generated by Django 4.2.11 on 2025-10-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_student_introduction_student_technology_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='introduction',
            new_name='account_introduction',
        ),
    ]
