# Generated by Django 4.2.11 on 2025-11-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('INTERNAL', '교내'), ('EXTERNAL', '교외'), ('LEARNING_MATERIAL', '학습 자료'), ('OPENSOURCE_REPO', '오픈소스 Repos'), ('EVENT_INFO', '행사 정보')], max_length=50)),
                ('is_internal', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('event_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'board_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=2048)),
                ('github_url', models.CharField(max_length=2048)),
                ('trending_rank', models.IntegerField()),
                ('developer_github_url', models.CharField(max_length=2048)),
                ('last_updated_date', models.DateField()),
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='trending_repo', to='board.post')),
            ],
            options={
                'db_table': 'board_trending_repo',
                'ordering': ['trending_rank'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('storage_link', models.CharField(max_length=2048)),
                ('file_extension', models.CharField(max_length=10)),
                ('display_type', models.CharField(choices=[('DOWNLOAD', 'Download'), ('WEB_VIEWER', 'Web Viewer')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.post')),
            ],
            options={
                'db_table': 'board_file',
            },
        ),
        migrations.CreateModel(
            name='CompanyRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=2048)),
                ('github_url', models.CharField(max_length=2048)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('repo_count', models.IntegerField(default=1)),
                ('last_updated_date', models.DateField()),
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='company_repo', to='board.post')),
            ],
            options={
                'db_table': 'board_company_repo',
            },
        ),
    ]
