# Generated by Django 5.1.4 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(
                choices=[
                    ('INTERNAL', '교내'),
                    ('EXTERNAL', '교외'),
                    ('LEARNING_MATERIAL', '학습 자료'),
                    ('OPENSOURCE_REPO', '오픈소스 Repos'),
                    ('EVENT_INFO', '행사 정보'),
                    ('QNA', 'Q&A'),
                ],
                max_length=50,
            ),
        ),
    ]
