# Generated by Django 4.2.11 on 2024-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='github_id',
        ),
        migrations.AddField(
            model_name='repository',
            name='crawled_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
