# Generated by Django 4.2.11 on 2024-05-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_remove_repository_github_id_repository_crawled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='contributor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='etc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='languate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='license',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='release_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
