# Generated by Django 4.2.11 on 2024-05-21 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_repository_contributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_contributor',
            fields=[
                ('repo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=255)),
                ('owner_github_id', models.CharField(max_length=255)),
                ('contributor_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repo_pr',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=255)),
                ('owner_github_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('requester_id', models.CharField(max_length=255)),
                ('published_date', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Repo_issue',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=255)),
                ('owner_github_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher_github_id', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Repo_commit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=255)),
                ('owner_github_id', models.CharField(max_length=255)),
                ('commiter_github_id', models.CharField(max_length=255)),
                ('added_lines', models.IntegerField()),
                ('deleted_lines', models.IntegerField()),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
    ]
