# Generated by Django 4.2.11 on 2024-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_repo_contributor_repo_pr_repo_issue_repo_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_commit',
            old_name='commiter_github_id',
            new_name='committer_github_id',
        ),
        migrations.AddField(
            model_name='repo_commit',
            name='last_update',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repo_issue',
            name='last_update',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repo_pr',
            name='last_update',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
