# Generated by Django 4.2.11 on 2024-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_rename_commiter_github_id_repo_commit_committer_github_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='has_readme',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner_github_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
