# Generated by Django 4.2.11 on 2024-05-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_alter_repository_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='contributor',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='languate',
            new_name='language',
        ),
    ]
