# Generated by Django 4.2.11 on 2024-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_rename_contributor_repository_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='contributors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='license',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner_github_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
