# Generated by Django 4.2.11 on 2024-05-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_alter_repository_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_issue',
            name='owner_github_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue',
            name='publisher_github_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue',
            name='repo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
