# Generated by Django 4.2.11 on 2024-05-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_alter_repo_issue_owner_github_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_pr',
            name='published_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pr',
            name='repo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pr',
            name='requester_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pr',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
