# Generated by Django 4.2.11 on 2024-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0010_alter_repo_pr_published_date_alter_repo_pr_repo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_commit',
            name='committer_github_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
