# Generated by Django 4.2.11 on 2024-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_alter_repo_commit_committer_github_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_commit',
            old_name='id',
            new_name='sha',
        ),
        migrations.AddConstraint(
            model_name='repo_commit',
            constraint=models.UniqueConstraint(fields=('sha', 'repo'), name='unique_repo_commit'),
        ),
    ]
