# Generated by Django 4.2.11 on 2024-05-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0012_rename_id_repo_commit_sha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo_commit',
        ),
    ]
