# Generated by Django 4.2.11 on 2024-05-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_delete_repo_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=255)),
                ('repo_url', models.CharField(max_length=255)),
                ('owner_github_id', models.CharField(max_length=255)),
                ('committer_github_id', models.CharField(max_length=255, null=True)),
                ('added_lines', models.IntegerField()),
                ('deleted_lines', models.IntegerField()),
                ('last_update', models.CharField(max_length=255, null=True)),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='repo_commit',
            constraint=models.UniqueConstraint(fields=('sha', 'repo'), name='unique_repo_commit'),
        ),
    ]
