# Generated by Django 4.2.11 on 2024-05-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_repo_commit_repo_commit_unique_repo_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo_contributor',
            name='contributor_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo_contributor',
            name='contributor_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
