# Generated by Django 4.2.11 on 2024-05-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0016_alter_repo_contributor_contributor_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_contributor',
            old_name='contributor_count',
            new_name='contribution_count',
        ),
        migrations.AddConstraint(
            model_name='repo_contributor',
            constraint=models.UniqueConstraint(fields=('repo_id', 'contributor_id'), name='unique_repo_contributor'),
        ),
    ]
