# Generated by Django 4.2.11 on 2024-05-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0017_rename_contributor_count_repo_contributor_contribution_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo_contributor',
        ),
    ]
