# Generated by Django 4.2.11 on 2024-05-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0019_repo_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repo_contributor',
            name='unique_repo_contributor',
        ),
    ]
