# Generated by Django 4.2.11 on 2024-05-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0020_remove_repo_contributor_unique_repo_contributor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repo_contributor',
            constraint=models.UniqueConstraint(fields=('repo_id', 'contributor_id'), name='unique_repo_contributor'),
        ),
    ]
