# Generated by Django 4.2.11 on 2024-05-27 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0022_delete_repo_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(max_length=255, null=True)),
                ('owner_github_id', models.CharField(max_length=255, null=True)),
                ('contributor_id', models.CharField(max_length=255, null=True)),
                ('contribution_count', models.IntegerField(null=True)),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='repo_contributor',
            constraint=models.UniqueConstraint(fields=('repo_id', 'contributor_id'), name='unique_repo_contributor'),
        ),
    ]
