# Generated by Django 4.2.11 on 2024-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0023_repo_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='closed_pr_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='open_pr_count',
            field=models.IntegerField(null=True),
        ),
    ]
