# Generated by Django 4.2.11 on 2024-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0025_alter_repository_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='forked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_closed_issue_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_commit_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_open_issue_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_open_pr_count',
            field=models.IntegerField(null=True),
        ),
    ]
