# Generated by Django 4.2.11 on 2024-11-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0026_repository_forked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_commit',
            old_name='committer_github_id',
            new_name='author_github_id',
        ),
    ]
