# Generated by Django 4.2.11 on 2024-11-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0027_rename_committer_github_id_repo_commit_author_github_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='owner_closed_issue_count',
            new_name='contributed_closed_issue_count',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='owner_commit_count',
            new_name='contributed_closed_pr_count',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='owner_open_issue_count',
            new_name='contributed_commit_count',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='owner_open_pr_count',
            new_name='contributed_open_issue_count',
        ),
        migrations.AddField(
            model_name='repository',
            name='contributed_open_pr_count',
            field=models.IntegerField(null=True),
        ),
    ]
