# Generated by Django 4.2.11 on 2025-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0028_rename_owner_closed_issue_count_repository_contributed_closed_issue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='language_bytes',
            field=models.JSONField(null=True),
        ),
    ]
