# Generated by Django 4.2.11 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0029_repository_language_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='language_percentage',
            field=models.JSONField(null=True),
        ),
    ]
