# Generated by Django 4.2.11 on 2025-08-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0030_repository_language_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
