# Generated by Django 4.2.11 on 2025-08-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0031_repository_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_course',
            field=models.BooleanField(null=True),
        ),
    ]
