# Generated by Django 4.2.11 on 2025-10-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0032_repository_category_repository_is_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repo_introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
